feat: constructing new Request object method
**Problem**

After using Hono validators, the `raw` Request obejct gets consumed
during body parsing, making it unusable for external libraries like
`better-auth`.
This results in the error:

```shell
TypeError: Cannot construct a Request with a Request object that has already been used.
```

**Root Cause**

The issue occurs in the `#cachedBody` method in `HonoRequest`. When parsing request
bodies (json, text, etc.), the method directly calls parsing methods on the raw Request
object, which consumes its body stream. Once consumed, the Request cannot be cloned or
reused by external libraries.

**Solution**

In a `new` method within `HonoRequest`, constructing a new Request
object that can be used even after it has been consumed by the validator
middleware.

If the `raw` Request object has already been consumed, then we store the
cached body in to the newly constructed Request object, and if it hasn't
then consume the body, cache it and then return it along the newly
constructed Request object.

Because we have created a new method, this should not degrade current
performance and should not introduce any breaking change.

Signed-off-by: Kamaal Farah <kamaal.f1@gmail.com>